### ISSUE TITLE
self.imageView.contentMode 

### ISSUE THREAD

**Issue by RanchenY** [choiceyou/FWCycleScrollView#1]
你好，
self.imageView.contentMode = .scaleToFill
这个属性能放出来吗？
谢谢

**Comment by choiceyou** [comment]
可以的，下个版本会开放出来的

**Comment by foqianyilishazi** [comment]
为什么OC使用Cocoapods 导入后库后，运行报错？

**Comment by choiceyou** [comment]
v2.1.0 类初始化方法使用 cycleAll 可以满足你的需求

**Comment by choiceyou** [comment]
@bujieshi 可以加群，把错误截图发出来
