### ISSUE TITLE
初始加载有动画效果

### ISSUE THREAD

**Issue by kwezdj123** [choiceyou/FWCycleScrollView#6]
ios13.3.1，XR

**Comment by kwezdj123** [comment]
创建banner，无限循环，首次加载图片时， 使用了动画。
滚动至中间页面时，其他页面也能看到，失去了无限循环的意义。
![截屏2020-08-17 上午10 22 07](https://user-images.githubusercontent.com/24710728/90351897-3b10b400-e074-11ea-8af9-6aa3f16839fc.png)

**Comment by choiceyou** [comment]
更新至2.1.4就可以了
